services:
  postgres:
    image: postgres:latest
    container_name: equipe
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: microservico-equipe
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "82:80"
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
